### ISSUE TITLE
Add mex lvlx for all combat engineer

### ISSUE THREAD

**Issue by skymyj** [Star-Annihilation/SA#3]
Is it a good idea ?

**Comment by Thorgram** [comment]
It could be nice to have the combat derivative mex and geo on the battle combat engineer, but since each tech is kept in the advanced con, it needs to be inferior and perhaps combat oriented so one does not spam combat engineers to tech up faster.

**Comment by skymyj** [comment]
Yes. I'm agree with you.
But ATM T4 builder engi comba have mex and fus. (it's historical). 
Maybe, we should delete this stuff (Op too make T4 Mex with flying builder) ?

**Comment by Thorgram** [comment]
It might be ok to have backup eco generation incase primary eco builders were destroyed, but for now putting them an eco tech backwards might be the easiest consistent solution. You might also consider a different gui from say Metal Factions that can make multiple menus so large buildmenus are less overwhelming and better categorized.

**Comment by skymyj** [comment]
Temporally delete eco structure for t5
