### ISSUE TITLE
Add TGA Talon Logo

### ISSUE THREAD

**Issue by skymyj** [Star-Annihilation/SA#4]
Hey Thorgasm. 
I post here what we said about talon logo. 

Need the Logo with : 
- Light texture (https://raw.githubusercontent.com/Star-Annihilation/SA/master/unittextures/tatex/pitgrey2vlight00.bmp)
- With light grey degrade 

Thank You

**Comment by Thorgram** [comment]
Your request has been filled, let me know how that functions.

**Comment by skymyj** [comment]
Thank you for you job ! 
Very nice !

**Comment by skymyj** [comment]
The texture are great. 
But the logo didn't take the color of team chosen. 
Tll took but not talon_logo. 
Do you know why ?
![image](https://user-images.githubusercontent.com/2990630/63891910-8e62a000-c9e6-11e9-88f6-1a91daa9e5d4.png)

**Comment by Thorgram** [comment]
Find a file inside the TATEX folder called teamtex, add the file to the list, make sure the upper and lower case match exactly in the name. 

https://github.com/Star-Annihilation/SA/blob/master/unittextures/tatex/teamtex.txt

**Comment by skymyj** [comment]
indeed. it works. 
that's why i never successfull.... 
Thank a lot!

**Comment by Thorgram** [comment]
No problem, show me another delicious image thanks. I'm glad i can help you.

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/63893689-2498c500-c9eb-11e9-8758-e39246bde78a.png)

**Comment by skymyj** [comment]
Ok. After many new relooking, we need a last tga texture. I see you .txt but atm no time to do. 
If you can add logo on this : CorVe01a
https://raw.githubusercontent.com/Star-Annihilation/SA/master/unittextures/tatex/corve01a00.bmp
Thanks!

Gift: Bertha T3 Kbot :)
![image](https://user-images.githubusercontent.com/2990630/63897881-fb7e3180-c9f6-11e9-8342-24d337913023.png)

**Comment by Thorgram** [comment]
Please Check Requested Texture in Same folder, it should work, I'll need another picture :) Don't forget teamtex.txt

**Comment by skymyj** [comment]
Thank Thorgasm. I'm at work, so i will check this evenning.
Finally, we regroup all faction in TA. Now I have the rights on the repository.
No image yet, but i made a new rapid bertha design :) and soon a rapid & all terrain ligting kbot
The faction have been tested many time and atm, pretty good balanced

**Comment by skymyj** [comment]
![image](https://user-images.githubusercontent.com/2990630/64654503-c1b31f00-d429-11e9-9926-47ab76f14661.png)
