### ISSUE TITLE
Rapid tool

### ISSUE THREAD

**Issue by skymyj** [Star-Annihilation/SA#6]
https://github.com/spring/RapidTools/issues/67#issuecomment-526373510
https://github.com/spring/pr-downloader/commit/8eab580589f99b4252cf23ad9ae12c31f5cdf1ed

**Comment by skymyj** [comment]
I think, it should be ok.

**Comment by ghost** [comment]
yes its working, host is up

**Comment by skymyj** [comment]
Is it possible to add text/info when there is new version like TA ?

**Comment by skymyj** [comment]
Need auto rehost after change (commits).
Atm all change are not integrated.
